defaultNetwork: hardhat
networks:
  hardhat:
    chainId: 1337
  localhost:
    url: http://127.0.0.1:8545

solidity:
  compilers:
    - version: "0.8.9"
      settings:
        optimizer:
          enabled: true
          runs: 200

paths:
  sources: "./contracts"
  tests: "./test"
  cache: "./cache"
  artifacts: "./artifacts"

mocha:
  timeout: 20000

plugins:
  - "@nomiclabs/hardhat-ethers"
  - "@nomiclabs/hardhat-waffle"
  - "@nomiclabs/hardhat-etherscan"
  - "solidity-coverage"

# Optional: If you want to configure Hardhat Etherscan plugin for contract verification
